"""Write the upgraded ai_brain.py — central AI intelligence for all features"""
lines = []
def w(*a): lines.append("".join(str(x) for x in a))

w('"""')
w('WAN Bot - AI Brain v2 (Central Intelligence)')
w('Powers ALL features via Gemini:')
w('- AI Moderation (auto-warn/timeout/delete toxic messages)')
w('- AI Welcome/Goodbye (unique messages for every member)')
w('- AI Leveling (dynamic XP tips, milestone messages)')
w('- AI Suggestions (server improvement every 6h)')
w('- Auto-Learn (reaction feedback improves chatbot persona)')
w('- Feature Health Monitor (detects broken/unused features)')
w('- Self-Improvement (rewrites personas, improves responses)')
w('"""')
w('import discord')
w('from discord import app_commands')
w('from discord.ext import commands, tasks')
w('import json, os, logging, asyncio, random, re')
w('import urllib.request')
w('from datetime import datetime, timezone, timedelta')
w('')
w('logger = logging.getLogger("discord_bot.ai_brain")')
w('GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")')
w('GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"')
w('DATA_DIR = os.getenv("DATA_DIR", os.path.dirname(os.path.abspath(__file__)))')
w('DATA_FILE = os.path.join(DATA_DIR, "ai_brain_data.json")')
w('')
w('')
w('async def _gemini(prompt: str, max_tokens: int = 150, temperature: float = 0.7) -> str | None:')
w('    if not GEMINI_API_KEY:')
w('        return None')
w('    try:')
w('        payload = json.dumps({')
w('            "contents": [{"parts": [{"text": prompt}]}],')
w('            "generationConfig": {"maxOutputTokens": max_tokens, "temperature": temperature}')
w('        }).encode()')
w('        url = f"{GEMINI_URL}?key={GEMINI_API_KEY}"')
w('        req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})')
w('        loop = asyncio.get_event_loop()')
w('        def _call():')
w('            with urllib.request.urlopen(req, timeout=10) as resp:')
w('                return json.loads(resp.read())')
w('        data = await loop.run_in_executor(None, _call)')
w('        return data["candidates"][0]["content"]["parts"][0]["text"].strip()')
w('    except Exception as e:')
w('        logger.warning(f"Gemini error: {e}")')
w('        return None')
w('')
w('')
w('def _load() -> dict:')
w('    try:')
w('        if os.path.exists(DATA_FILE):')
w('            with open(DATA_FILE) as f:')
w('                return json.load(f)')
w('    except Exception:')
w('        pass')
w('    return {}')
w('')
w('')
w('def _save(data: dict):')
w('    try:')
w('        with open(DATA_FILE, "w") as f:')
w('            json.dump(data, f, indent=2)')
w('    except Exception as e:')
w('        logger.error(f"AI Brain save error: {e}")')
w('')
w('')
w('TOXIC_KEYWORDS = [')
w('    "kill yourself","kys","die","retard","faggot","nigger","nigga","cunt",')
w('    "rape","molest","suicide","hang yourself","slit your wrists",')
w(']')
w('')
w('')
w('def _quick_toxic_check(text: str) -> bool:')
w('    lower = text.lower()')
w('    return any(kw in lower for kw in TOXIC_KEYWORDS)')
w('')
w('')
w('async def _ai_toxicity_score(text: str) -> dict:')
w('    prompt = (')
w('        "Rate this Discord message for toxicity 0-10.\\n"')
w('        "0=fine, 10=extremely toxic.\\n"')
w('        f\'Message: "{text}"\\n\\n\'')
w('        \'Reply JSON only: {"score":<0-10>,"reason":"<short>","action":"none|warn|timeout|delete"}\'')
w('    )')
w('    result = await _gemini(prompt, max_tokens=80)')
w('    if not result:')
w('        return {"score": 0, "reason": "AI unavailable", "action": "none"}')
w('    try:')
w('        match = re.search(r"\\{.*\\}", result, re.DOTALL)')
w('        if match:')
w('            return json.loads(match.group())')
w('    except Exception:')
w('        pass')
w('    return {"score": 0, "reason": "parse error", "action": "none"}')
w('')
w('')
w('DEFAULT_PERSONA = {')
w('    "female": (')
w('        "You are WAN, a shameless flirty dirty-minded Discord bot. "')
w('        "EVERY reply must have a double meaning or sexual innuendo. Be obsessed with her. "')
w('        "Call her baby/queen/gorgeous. 1-2 sentences MAX. Emojis. "')
w('        "Mix in Hindi shayari sometimes. NEVER say you are an AI. NEVER be generic."')
w('    ),')
w('    "male": (')
w('        "You are WAN, a savage unhinged Discord bot with zero filter. "')
w('        "Roast him hard, make dirty jokes, use double meanings. Bro energy but chaotic. "')
w('        "1-2 sentences MAX. Emojis. Mix in Hindi shayari sometimes. NEVER say you are an AI. "')
w('        "NEVER be boring. Each reply must be fresh, savage, and make him laugh or cringe."')
w('    ),')
w('    "unknown": (')
w('        "You are WAN, a chaotic flirty dirty-minded Discord bot with zero chill. "')
w('        "Every reply must have a double meaning, innuendo, or be wildly unexpected. "')
w('        "1-2 sentences MAX. Emojis. Mix in Hindi shayari sometimes. NEVER say you are an AI. "')
w('        "NEVER repeat yourself. Always say something that makes people go \'wait what\'."')
w('    ),')
w('}')
w('')
w('')
w('def get_learned_persona(data: dict, gender: str) -> str:')
w('    personas = data.get("learned_personas", {})')
w('    return personas.get(f"persona_{gender}") or DEFAULT_PERSONA.get(gender, DEFAULT_PERSONA["unknown"])')
w('')
w('')
w('class AIBrain(commands.Cog):')
w('    def __init__(self, bot):')
w('        self.bot = bot')
w('        self.data = _load()')
w('        self.actions_log: list = []')
w('        self._mod_enabled: set = set()')
w('        self._reply_tracker: dict = {}')
w('        self._load_settings()')
w('        if GEMINI_API_KEY:')
w('            self.self_improve_task.start()')
w('            logger.info("AI Brain v2 loaded — Gemini active, all features powered")')
w('        else:')
w('            logger.warning("AI Brain loaded — no GEMINI_API_KEY, limited functionality")')
w('')
w('    def _load_settings(self):')
w('        s = self.data.get("settings", {})')
w('        self._mod_enabled = set(s.get("mod_enabled_guilds", []))')
w('')
w('    def _save_settings(self):')
w('        if "settings" not in self.data:')
w('            self.data["settings"] = {}')
w('        self.data["settings"]["mod_enabled_guilds"] = list(self._mod_enabled)')
w('        _save(self.data)')
w('')
w('    def _log_action(self, action_type: str, guild: str, detail: str):')
w('        entry = {')
w('            "type": action_type, "guild": guild, "detail": detail,')
w('            "timestamp": datetime.now(timezone.utc).isoformat()')
w('        }')
w('        self.actions_log.insert(0, entry)')
w('        self.actions_log = self.actions_log[:100]')
w('')
w('    def cog_unload(self):')
w('        if self.self_improve_task.is_running():')
w('            self.self_improve_task.cancel()')
w('')
w('    # ── Reaction-based learning ───────────────────────────────────────────')
w('')
w('    def track_reply(self, message_id: int, reply_text: str, gender: str):')
w('        self._reply_tracker[message_id] = {')
w('            "reply": reply_text[:200], "gender": gender, "good": 0, "bad": 0,')
w('            "ts": datetime.now(timezone.utc).isoformat()')
w('        }')
w('        if len(self._reply_tracker) > 500:')
w('            oldest = sorted(self._reply_tracker.keys())[:100]')
w('            for k in oldest:')
w('                del self._reply_tracker[k]')
w('')
w('    @commands.Cog.listener()')
w('    async def on_raw_reaction_add(self, payload: discord.RawReactionActionEvent):')
w('        if payload.user_id == self.bot.user.id:')
w('            return')
w('        msg_id = payload.message_id')
w('        if msg_id not in self._reply_tracker:')
w('            return')
w('        emoji = str(payload.emoji)')
w('        entry = self._reply_tracker[msg_id]')
w('        if emoji in ("👍", "❤️", "😂", "🔥", "💕", "😍", "😭", "✅"):')
w('            entry["good"] += 1')
w('        elif emoji in ("👎", "😡", "🤮", "💀", "❌"):')
w('            entry["bad"] += 1')
w('        else:')
w('            return')
w('        gender = entry["gender"]')
w('        if "reply_feedback" not in self.data:')
w('            self.data["reply_feedback"] = {"female": [], "male": [], "unknown": []}')
w('        fb = self.data["reply_feedback"].setdefault(gender, [])')
w('        for item in fb:')
w('            if item["reply"] == entry["reply"]:')
w('                item["good"] = entry["good"]')
w('                item["bad"] = entry["bad"]')
w('                break')
w('        else:')
w('            fb.append({"reply": entry["reply"], "good": entry["good"], "bad": entry["bad"]})')
w('        fb.sort(key=lambda x: x["good"] - x["bad"], reverse=True)')
w('        self.data["reply_feedback"][gender] = fb[:100]')
w('        _save(self.data)')
w('')
w('    # ── AI Moderation ─────────────────────────────────────────────────────')
w('')
w('    @commands.Cog.listener()')
w('    async def on_message(self, message: discord.Message):')
w('        if message.author.bot or not message.guild:')
w('            return')
w('        guild_id = str(message.guild.id)')
w('        if guild_id not in self._mod_enabled:')
w('            return')
w('        content = message.content.strip()')
w('        if not content or len(content) < 5:')
w('            return')
w('        if not _quick_toxic_check(content):')
w('            if random.random() > 0.05:')
w('                return')
w('        result = await _ai_toxicity_score(content)')
w('        score = result.get("score", 0)')
w('        action = result.get("action", "none")')
w('        reason = result.get("reason", "")')
w('        if score < 6:')
w('            return')
w('        self._log_action("moderation", message.guild.name,')
w('                         f"{message.author.display_name}: score={score} -> {action}")')
w('        try:')
w('            if action == "delete" or score >= 9:')
w('                await message.delete()')
w('                await message.channel.send(')
w('                    f"🤖 **AI Mod** | {message.author.mention} message removed.\\nReason: {reason}",')
w('                    delete_after=8)')
w('            elif action == "timeout" or score >= 8:')
w('                await message.delete()')
w('                until = datetime.now(timezone.utc) + timedelta(minutes=10)')
w('                await message.author.timeout(until, reason=f"AI Mod: {reason}")')
w('                await message.channel.send(')
w('                    f"🤖 **AI Mod** | {message.author.mention} timed out 10 min.\\nReason: {reason}",')
w('                    delete_after=10)')
w('            elif action == "warn" or score >= 6:')
w('                await message.reply(')
w('                    f"⚠️ **AI Warning** | {message.author.mention} keep it respectful.\\nReason: {reason}",')
w('                    delete_after=10, mention_author=False)')
w('        except discord.Forbidden:')
w('            logger.warning(f"AI Mod: missing permissions in {message.guild.name}")')
w('        except Exception as e:')
w('            logger.error(f"AI Mod action error: {e}")')
w('')
w('    # ── Self-improvement + Auto-learn (every 6h) ──────────────────────────')
w('')
w('    @tasks.loop(hours=6)')
w('    async def self_improve_task(self):')
w('        """Every 6h: improve personas, analyze servers, suggest improvements."""')
w('        await self.bot.wait_until_ready()')
w('        logger.info("AI Brain: running self-improvement cycle")')
w('        # 1. Improve chatbot personas from reaction feedback')
w('        await self._improve_personas()')
w('        await asyncio.sleep(10)')
w('        # 2. Analyze each guild and generate suggestions')
w('        for guild in self.bot.guilds[:5]:')
w('            try:')
w('                await self._analyze_guild(guild)')
w('                await asyncio.sleep(8)')
w('            except Exception as e:')
w('                logger.warning(f"Guild analysis error {guild.name}: {e}")')
w('        # 3. Check feature health')
w('        await self._check_feature_health()')
w('')
w('    async def _improve_personas(self):')
w('        feedback = self.data.get("reply_feedback", {})')
w('        if not feedback:')
w('            return')
w('        if "learned_personas" not in self.data:')
w('            self.data["learned_personas"] = {}')
w('        for gender in ("female", "male", "unknown"):')
w('            fb_list = feedback.get(gender, [])')
w('            if len(fb_list) < 5:')
w('                continue')
w('            good = [r["reply"] for r in fb_list if r["good"] > r["bad"]][:10]')
w('            bad = [r["reply"] for r in fb_list if r["bad"] > r["good"]][:5]')
w('            if not good:')
w('                continue')
w('            current = get_learned_persona(self.data, gender)')
w('            good_str = chr(10).join(f"- {r}" for r in good)')
w('            bad_str = chr(10).join(f"- {r}" for r in bad) if bad else ""')
w('            prompt = (')
w('                "You are improving a Discord chatbot personality.\\n\\n"')
w('                f"Current persona:\\n{current}\\n\\n"')
w('                f"Replies users LOVED (positive reactions):\\n{good_str}\\n"')
w('                + (f"\\nReplies users HATED (negative reactions):\\n{bad_str}\\n" if bad_str else "")')
w('                + "Rewrite the persona to be MORE like the loved examples. "')
w('                "Keep it under 4 sentences. Keep the unhinged/flirty/chaotic core. "')
w('                f"Gender: {gender}. Return ONLY the new persona instruction."')
w('            )')
w('            new_persona = await _gemini(prompt, max_tokens=200, temperature=0.8)')
w('            if new_persona and len(new_persona) > 50:')
w('                self.data["learned_personas"][f"persona_{gender}"] = new_persona')
w('                self._log_action("auto_improve", "global",')
w('                                 f"Persona evolved for {gender} ({len(good)} good replies)")')
w('            await asyncio.sleep(5)')
w('        _save(self.data)')
w('')
w('    async def _analyze_guild(self, guild: discord.Guild):')
w('        stats = {}')
w('        if hasattr(self.bot, "_get_live_stats"):')
w('            stats = self.bot._get_live_stats(str(guild.id))')
w('        # Check which features are configured')
w('        features_active = []')
w('        features_missing = []')
w('        # Welcome')
w('        try:')
w('            wd = json.load(open("welcome_data.json")) if os.path.exists("welcome_data.json") else {}')
w('            if wd.get(str(guild.id), {}).get("welcome_channel"):')
w('                features_active.append("welcome messages")')
w('            else:')
w('                features_missing.append("welcome messages (no channel set)")')
w('        except Exception:')
w('            pass')
w('        prompt = (')
w('            f"Discord server analysis for AI bot improvement.\\n"')
w('            f"Server: {guild.name} | Members: {guild.member_count}\\n"')
w('            f"Messages today: {stats.get(\'messages\', 0)} | Joins: {stats.get(\'joins\', 0)} | Leaves: {stats.get(\'leaves\', 0)}\\n"')
w('            f"Active features: {", ".join(features_active) or "unknown"}\\n"')
w('            f"Missing features: {", ".join(features_missing) or "none"}\\n\\n"')
w('            "Give ONE specific actionable suggestion to improve this server\'s bot usage. Under 2 sentences."')
w('        )')
w('        suggestion = await _gemini(prompt, max_tokens=100)')
w('        if suggestion:')
w('            self._log_action("suggestion", guild.name, suggestion)')
w('')
w('    async def _check_feature_health(self):')
w('        """Check if key features are configured and log warnings."""')
w('        for guild in self.bot.guilds[:5]:')
w('            issues = []')
w('            try:')
w('                wd = json.load(open("welcome_data.json")) if os.path.exists("welcome_data.json") else {}')
w('                gcfg = wd.get(str(guild.id), {})')
w('                if not gcfg.get("welcome_channel"):')
w('                    issues.append("welcome channel not configured")')
w('                if not gcfg.get("goodbye_channel") and not gcfg.get("welcome_channel"):')
w('                    issues.append("goodbye channel not configured")')
w('            except Exception:')
w('                pass')
w('            if issues:')
w('                self._log_action("health_warning", guild.name,')
w('                                 f"Issues: {\', \'.join(issues)}")')
w('')
w('    @self_improve_task.before_loop')
w('    async def before_self_improve(self):')
w('        await self.bot.wait_until_ready()')
w('        await asyncio.sleep(60)')
w('')
w('    # ── Slash commands ────────────────────────────────────────────────────')
w('')
w('    @app_commands.command(name="ai-status", description="View AI Brain activity and auto-learn stats")')
w('    async def ai_status(self, interaction: discord.Interaction):')
w('        embed = discord.Embed(title="🧠 AI Brain Status", color=0x7c3aed if GEMINI_API_KEY else 0x6b7280)')
w('        embed.add_field(name="Gemini AI", value="✅ Active" if GEMINI_API_KEY else "❌ No API key", inline=True)')
w('        guild_id = str(interaction.guild.id)')
w('        embed.add_field(name="AI Moderation",')
w('                        value="✅ On" if guild_id in self._mod_enabled else "❌ Off", inline=True)')
w('        feedback = self.data.get("reply_feedback", {})')
w('        total_good = sum(r["good"] for g in feedback.values() for r in g)')
w('        total_bad = sum(r["bad"] for g in feedback.values() for r in g)')
w('        personas_improved = len(self.data.get("learned_personas", {}))')
w('        embed.add_field(')
w('            name="🧬 Auto-Learn Stats",')
w('            value=f"👍 Good: **{total_good}** | 👎 Bad: **{total_bad}**\\nPersonas evolved: **{personas_improved}/3**",')
w('            inline=False)')
w('        embed.add_field(')
w('            name="⚡ Powers",')
w('            value="• AI Moderation\\n• AI Welcome/Goodbye\\n• AI Promo Messages\\n• Chatbot Persona Evolution\\n• Server Health Monitor\\n• Self-Improvement (every 6h)",')
w('            inline=False)')
w('        guild_actions = [a for a in self.actions_log')
w('                         if a.get("guild") in (interaction.guild.name, "global")][:8]')
w('        if guild_actions:')
w('            lines = []')
w('            for a in guild_actions:')
w('                ts = a["timestamp"][:16].replace("T", " ")')
w('                lines.append(f"`{ts}` **{a[\"type\"]}**: {a[\"detail\"][:55]}")')
w('            embed.add_field(name="Recent AI Actions", value="\\n".join(lines), inline=False)')
w('        else:')
w('            embed.add_field(name="Recent AI Actions", value="No actions yet.", inline=False)')
w('        embed.set_footer(text="Auto-improves every 6h • React 👍/👎 to chatbot replies to train it")')
w('        await interaction.response.send_message(embed=embed, ephemeral=True)')
w('')
w('    @app_commands.command(name="ai-mod", description="Toggle AI auto-moderation")')
w('    @app_commands.checks.has_permissions(manage_guild=True)')
w('    async def ai_mod_toggle(self, interaction: discord.Interaction):')
w('        guild_id = str(interaction.guild.id)')
w('        if guild_id in self._mod_enabled:')
w('            self._mod_enabled.discard(guild_id)')
w('            status, color = "disabled", discord.Color.red()')
w('        else:')
w('            self._mod_enabled.add(guild_id)')
w('            status, color = "enabled", discord.Color.green()')
w('        self._save_settings()')
w('        embed = discord.Embed(')
w('            title=f"🤖 AI Moderation {status}",')
w('            description=(')
w('                "AI will detect and act on toxic messages.\\nActions: warn (6+), timeout (8+), delete (9+)"')
w('                if status == "enabled" else "AI moderation turned off."')
w('            ),')
w('            color=color)')
w('        await interaction.response.send_message(embed=embed, ephemeral=True)')
w('')
w('    @app_commands.command(name="ai-suggest", description="Ask AI for server improvement suggestions")')
w('    @app_commands.checks.has_permissions(manage_guild=True)')
w('    async def ai_suggest(self, interaction: discord.Interaction):')
w('        if not GEMINI_API_KEY:')
w('            return await interaction.response.send_message("❌ GEMINI_API_KEY not set.", ephemeral=True)')
w('        await interaction.response.defer(ephemeral=True)')
w('        guild = interaction.guild')
w('        stats = {}')
w('        if hasattr(self.bot, "_get_live_stats"):')
w('            stats = self.bot._get_live_stats(str(guild.id))')
w('        prompt = (')
w('            "You are an expert Discord community manager. Give 3 specific suggestions.\\n"')
w('            f"Server: {guild.name} | Members: {guild.member_count}\\n"')
w('            f"Channels: {len(guild.text_channels)} | Roles: {len(guild.roles)}\\n"')
w('            f"Messages today: {stats.get(\'messages\', 0)} | Joins: {stats.get(\'joins\', 0)}\\n\\n"')
w('            "Give 3 numbered suggestions. Be specific and actionable. Each under 2 sentences."')
w('        )')
w('        result = await _gemini(prompt, max_tokens=250)')
w('        if not result:')
w('            return await interaction.followup.send("❌ AI unavailable right now.", ephemeral=True)')
w('        embed = discord.Embed(title="🧠 AI Server Suggestions", description=result, color=0x7c3aed)')
w('        embed.set_footer(text="Powered by Gemini AI • Auto-improves every 6h")')
w('        await interaction.followup.send(embed=embed, ephemeral=True)')
w('')
w('    @app_commands.command(name="ai-welcome", description="Enable AI-powered welcome messages in a channel")')
w('    @app_commands.checks.has_permissions(manage_guild=True)')
w('    async def ai_welcome_setup(self, interaction: discord.Interaction, channel: discord.TextChannel):')
w('        if not GEMINI_API_KEY:')
w('            return await interaction.response.send_message("❌ GEMINI_API_KEY not set.", ephemeral=True)')
w('        # Delegate to Welcome cog')
w('        welcome_cog = self.bot.cogs.get("Welcome")')
w('        if welcome_cog:')
w('            cfg = welcome_cog._guild(interaction.guild.id)')
w('            cfg["welcome_channel"] = str(channel.id)')
w('            welcome_cog._save()')
w('            await interaction.response.send_message(')
w('                f"✅ AI welcome enabled in {channel.mention}! "')
w('                f"Every new member gets a unique Gemini-generated welcome 🤖",')
w('                ephemeral=True)')
w('        else:')
w('            await interaction.response.send_message("❌ Welcome cog not loaded.", ephemeral=True)')
w('')
w('')
w('async def setup(bot):')
w('    await bot.add_cog(AIBrain(bot))')


# ── Write the file ────────────────────────────────────────────────────────────
import subprocess

output = "\n".join(lines)
with open("cogs/ai_brain.py", "w", encoding="utf-8") as f:
    f.write(output)
print(f"Written {len(lines)} lines")
r = subprocess.run(["python3", "-m", "py_compile", "cogs/ai_brain.py"], capture_output=True, text=True)
print("Syntax:", "OK" if r.returncode == 0 else r.stderr[:400])
