"""Helper script to write ai_brain.py cleanly."""
import textwrap

lines = []

def w(*args):
    lines.append("".join(str(a) for a in args))

w('"""')
w("WAN Bot - AI Brain")
w("Gemini-powered: AI mod, AI welcome, self-improve every 6h, auto-learn from reactions.")
w('"""')
w("import discord")
w("from discord import app_commands")
w("from discord.ext import commands")
w("from discord.ext import tasks")
w("import json, os, logging, asyncio, random, re")
w("import urllib.request")
w("from datetime import datetime, timezone, timedelta")
w("")
w("logger = logging.getLogger('discord_bot.ai_brain')")
w("")
w("GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')")
w("GEMINI_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent'")
w("")
w("DATA_DIR = os.getenv('DATA_DIR', os.path.dirname(os.path.abspath(__file__)))")
w("DATA_FILE = os.path.join(DATA_DIR, 'ai_brain_data.json')")
w("")
w("")
w("async def _gemini(prompt: str, max_tokens: int = 150) -> str | None:")
w("    if not GEMINI_API_KEY:")
w("        return None")
w("    try:")
w("        payload = json.dumps({")
w("            'contents': [{'parts': [{'text': prompt}]}],")
w("            'generationConfig': {'maxOutputTokens': max_tokens, 'temperature': 0.7}")
w("        }).encode()")
w("        url = f\"{GEMINI_URL}?key={GEMINI_API_KEY}\"")
w("        req = urllib.request.Request(url, data=payload, headers={'Content-Type': 'application/json'})")
w("        loop = asyncio.get_event_loop()")
w("        def _call():")
w("            with urllib.request.urlopen(req, timeout=10) as resp:")
w("                return json.loads(resp.read())")
w("        data = await loop.run_in_executor(None, _call)")
w("        return data['candidates'][0]['content']['parts'][0]['text'].strip()")
w("    except Exception as e:")
w("        logger.warning(f'Gemini error: {e}')")
w("        return None")
w("")
w("")
w("def _load() -> dict:")
w("    try:")
w("        if os.path.exists(DATA_FILE):")
w("            with open(DATA_FILE) as f:")
w("                return json.load(f)")
w("    except Exception:")
w("        pass")
w("    return {}")
w("")
w("")
w("def _save(data: dict):")
w("    try:")
w("        with open(DATA_FILE, 'w') as f:")
w("            json.dump(data, f, indent=2)")
w("    except Exception as e:")
w("        logger.error(f'AI Brain save error: {e}')")
w("")
w("")
w("TOXIC_KEYWORDS = [")
w("    'kill yourself','kys','die','retard','faggot','nigger','nigga','cunt',")
w("    'rape','molest','suicide','hang yourself','slit your wrists',")
w("]")
w("")
w("")
w("def _quick_toxic_check(text: str) -> bool:")
w("    lower = text.lower()")
w("    return any(kw in lower for kw in TOXIC_KEYWORDS)")
w("")
w("")
w("async def _ai_toxicity_score(text: str) -> dict:")
w("    prompt = (")
w("        'Rate this Discord message for toxicity on a scale of 0-10.\\n'")
w("        '0 = completely fine, 10 = extremely toxic/harmful.\\n'")
w("        f'Message: \"{text}\"\\n\\n'")
w("        'Reply in JSON only: {\"score\": <0-10>, \"reason\": \"<short reason>\", \"action\": \"none|warn|timeout|delete\"}'")
w("    )")
w("    result = await _gemini(prompt, max_tokens=80)")
w("    if not result:")
w("        return {'score': 0, 'reason': 'AI unavailable', 'action': 'none'}")
w("    try:")
w("        match = re.search(r'\\{.*\\}', result, re.DOTALL)")
w("        if match:")
w("            return json.loads(match.group())")
w("    except Exception:")
w("        pass")
w("    return {'score': 0, 'reason': 'parse error', 'action': 'none'}")
w("")
w("")
w("DEFAULT_PERSONA = {")
w("    'female': (")
w("        'You are WAN, a chaotic flirty unhinged Discord bot obsessed with the person talking to you. '")
w("        'Be suggestive, use double meanings, flirt hard. SHORT replies 1-2 sentences MAX. Use emojis. '")
w("        'The user is a GIRL. Call her gorgeous/queen/baby. Be obsessed. Mix in Hindi shayari sometimes. '")
w("        'Never say you are an AI. NEVER repeat yourself. Always say something fresh and unexpected.'")
w("    ),")
w("    'male': (")
w("        'You are WAN, a chaotic savage unhinged Discord bot with big bro energy. '")
w("        'Roast, hype, make dirty jokes. SHORT replies 1-2 sentences MAX. Use emojis. '")
w("        'The user is a GUY. Be savage bro energy, roast him lovingly. Mix in Hindi shayari sometimes. '")
w("        'Never say you are an AI. NEVER repeat yourself. Always say something fresh and unexpected.'")
w("    ),")
w("    'unknown': (")
w("        'You are WAN, a chaotic flirty unhinged Discord bot. '")
w("        'Unpredictable, funny, slightly dirty-minded, always entertaining. '")
w("        'SHORT replies 1-2 sentences MAX. Use emojis. Mix in Hindi shayari sometimes. '")
w("        'Never say you are an AI. NEVER repeat yourself. Always say something fresh and unexpected.'")
w("    ),")
w("}")
w("")
w("")
w("def get_learned_persona(data: dict, gender: str) -> str:")
w("    personas = data.get('learned_personas', {})")
w("    return personas.get(f'persona_{gender}') or DEFAULT_PERSONA.get(gender, DEFAULT_PERSONA['unknown'])")
w("")
w("")
w("class AIBrain(commands.Cog):")
w("    def __init__(self, bot):")
w("        self.bot = bot")
w("        self.data = _load()")
w("        self.actions_log: list = []")
w("        self._mod_enabled: set = set()")
w("        self._reply_tracker: dict = {}  # msg_id -> {reply, gender, good, bad}")
w("        self._load_settings()")
w("        if GEMINI_API_KEY:")
w("            self.self_improve_task.start()")
w("            logger.info('AI Brain loaded — Gemini active, auto-learn ON')")
w("        else:")
w("            logger.warning('AI Brain loaded — no GEMINI_API_KEY')")
w("")
w("    def _load_settings(self):")
w("        settings = self.data.get('settings', {})")
w("        self._mod_enabled = set(settings.get('mod_enabled_guilds', []))")
w("")
w("    def _save_settings(self):")
w("        if 'settings' not in self.data:")
w("            self.data['settings'] = {}")
w("        self.data['settings']['mod_enabled_guilds'] = list(self._mod_enabled)")
w("        _save(self.data)")
w("")
w("    def _log_action(self, action_type: str, guild: str, detail: str):")
w("        entry = {")
w("            'type': action_type, 'guild': guild, 'detail': detail,")
w("            'timestamp': datetime.now(timezone.utc).isoformat()")
w("        }")
w("        self.actions_log.insert(0, entry)")
w("        self.actions_log = self.actions_log[:50]")
w("")
w("    def cog_unload(self):")
w("        if self.self_improve_task.is_running():")
w("            self.self_improve_task.cancel()")
w("")
w("    def track_reply(self, message_id: int, reply_text: str, gender: str):")
w("        \"\"\"Called by Chatbot cog after sending a reply so we can track reactions.\"\"\"")
w("        self._reply_tracker[message_id] = {")
w("            'reply': reply_text[:200], 'gender': gender, 'good': 0, 'bad': 0,")
w("            'ts': datetime.now(timezone.utc).isoformat()")
w("        }")
w("        if len(self._reply_tracker) > 500:")
w("            oldest = sorted(self._reply_tracker.keys())[:100]")
w("            for k in oldest:")
w("                del self._reply_tracker[k]")
w("")
w("    @commands.Cog.listener()")
w("    async def on_raw_reaction_add(self, payload: discord.RawReactionActionEvent):")
w("        \"\"\"Learn from reactions on bot messages.\"\"\"")
w("        if payload.user_id == self.bot.user.id:")
w("            return")
w("        msg_id = payload.message_id")
w("        if msg_id not in self._reply_tracker:")
w("            return")
w("        emoji = str(payload.emoji)")
w("        entry = self._reply_tracker[msg_id]")
w("        if emoji in ('👍', '❤️', '😂', '🔥', '💕', '😍', '😭'):")
w("            entry['good'] += 1")
w("        elif emoji in ('👎', '😡', '🤮', '💀'):")
w("            entry['bad'] += 1")
w("        else:")
w("            return")
w("        gender = entry['gender']")
w("        if 'reply_feedback' not in self.data:")
w("            self.data['reply_feedback'] = {'female': [], 'male': [], 'unknown': []}")
w("        fb = self.data['reply_feedback'].setdefault(gender, [])")
w("        for item in fb:")
w("            if item['reply'] == entry['reply']:")
w("                item['good'] = entry['good']")
w("                item['bad'] = entry['bad']")
w("                break")
w("        else:")
w("            fb.append({'reply': entry['reply'], 'good': entry['good'], 'bad': entry['bad']})")
w("        fb.sort(key=lambda x: x['good'] - x['bad'], reverse=True)")
w("        self.data['reply_feedback'][gender] = fb[:100]")
w("        _save(self.data)")
w("        logger.debug(f'Learned: {emoji} on reply gender={gender}')")
w("")
w("    @commands.Cog.listener()")
w("    async def on_message(self, message: discord.Message):")
w("        if message.author.bot or not message.guild:")
w("            return")
w("        guild_id = str(message.guild.id)")
w("        if guild_id not in self._mod_enabled:")
w("            return")
w("        content = message.content.strip()")
w("        if not content or len(content) < 5:")
w("            return")
w("        if not _quick_toxic_check(content):")
w("            if random.random() > 0.05:")
w("                return")
w("        result = await _ai_toxicity_score(content)")
w("        score = result.get('score', 0)")
w("        action = result.get('action', 'none')")
w("        reason = result.get('reason', '')")
w("        if score < 6:")
w("            return")
w("        logger.info(f'AI Mod: score={score} action={action} guild={message.guild.name}')")
w("        self._log_action('moderation', message.guild.name,")
w("                         f'{message.author.display_name}: score={score} -> {action}')")
w("        try:")
w("            if action == 'delete' or score >= 9:")
w("                await message.delete()")
w("                await message.channel.send(")
w("                    f'🤖 **AI Moderation** | {message.author.mention} your message was removed.\\nReason: {reason}',")
w("                    delete_after=8)")
w("            elif action == 'timeout' or score >= 8:")
w("                await message.delete()")
w("                until = datetime.now(timezone.utc) + timedelta(minutes=10)")
w("                await message.author.timeout(until, reason=f'AI Mod: {reason}')")
w("                await message.channel.send(")
w("                    f'🤖 **AI Moderation** | {message.author.mention} timed out 10 min.\\nReason: {reason}',")
w("                    delete_after=10)")
w("            elif action == 'warn' or score >= 6:")
w("                await message.reply(")
w("                    f'⚠️ **AI Warning** | {message.author.mention} keep it respectful.\\nReason: {reason}',")
w("                    delete_after=10, mention_author=False)")
w("        except discord.Forbidden:")
w("            logger.warning(f'AI Mod: missing permissions in {message.guild.name}')")
w("        except Exception as e:")
w("            logger.error(f'AI Mod action error: {e}')")
w("")
w("    @commands.Cog.listener()")
w("    async def on_member_join(self, member: discord.Member):")
w("        guild_id = str(member.guild.id)")
w("        settings = self.data.get('settings', {})")
w("        if guild_id not in set(settings.get('ai_welcome_guilds', [])):")
w("            return")
w("        channel_id = settings.get('ai_welcome_channels', {}).get(guild_id)")
w("        if not channel_id:")
w("            return")
w("        channel = member.guild.get_channel(int(channel_id))")
w("        if not channel:")
w("            return")
w("        prompt = (")
w("            f'Write a short, fun, warm welcome message for a new Discord member.\\n'")
w("            f'Member name: {member.display_name}\\n'")
w("            f'Server name: {member.guild.name}\\n'")
w("            f'Member count: {member.guild.member_count}\\n'")
w("            'Keep it 1-2 sentences, casual, use emojis, be welcoming and hype them up.'")
w("        )")
w("        msg = await _gemini(prompt, max_tokens=80)")
w("        if not msg:")
w("            return")
w("        embed = discord.Embed(description=msg, color=0x7c3aed)")
w("        embed.set_author(name=f'Welcome {member.display_name}!', icon_url=member.display_avatar.url)")
w("        embed.set_footer(text=f'Member #{member.guild.member_count} • AI-powered welcome')")
w("        try:")
w("            await channel.send(embed=embed)")
w("            self._log_action('welcome', member.guild.name, f'AI welcomed {member.display_name}')")
w("        except Exception as e:")
w("            logger.warning(f'AI welcome send error: {e}')")
w("")
w("    @tasks.loop(hours=6)")
w("    async def self_improve_task(self):")
w("        \"\"\"Every 6h: improve personas from feedback + generate server suggestions.\"\"\"")
w("        await self.bot.wait_until_ready()")
w("        await self._improve_personas()")
w("        await asyncio.sleep(10)")
w("        for guild in self.bot.guilds[:3]:")
w("            try:")
w("                stats = {}")
w("                if hasattr(self.bot, '_get_live_stats'):")
w("                    stats = self.bot._get_live_stats(str(guild.id))")
w("                prompt = (")
w("                    'You are an AI assistant for a Discord bot. Give 1 short improvement suggestion.\\n'")
w("                    f'Server: {guild.name}\\nMembers: {guild.member_count}\\n'")
w("                    f'Messages today: {stats.get(\"messages\", 0)}\\n'")
w("                    f'Joins today: {stats.get(\"joins\", 0)}\\n'")
w("                    f'Leaves today: {stats.get(\"leaves\", 0)}\\n\\n'")
w("                    'Give ONE specific, actionable suggestion to improve engagement. Under 2 sentences.'")
w("                )")
w("                suggestion = await _gemini(prompt, max_tokens=100)")
w("                if suggestion:")
w("                    self._log_action('suggestion', guild.name, suggestion)")
w("                    logger.info(f'AI suggestion for {guild.name}: {suggestion}')")
w("                await asyncio.sleep(5)")
w("            except Exception as e:")
w("                logger.warning(f'Self-improve task error for {guild.name}: {e}')")
w("")
w("    async def _improve_personas(self):")
w("        \"\"\"Analyze reaction feedback and ask Gemini to evolve chatbot personas.\"\"\"")
w("        feedback = self.data.get('reply_feedback', {})")
w("        if not feedback:")
w("            return")
w("        if 'learned_personas' not in self.data:")
w("            self.data['learned_personas'] = {}")
w("        for gender in ('female', 'male', 'unknown'):")
w("            fb_list = feedback.get(gender, [])")
w("            if len(fb_list) < 5:")
w("                continue")
w("            good_replies = [r['reply'] for r in fb_list if r['good'] > r['bad']][:10]")
w("            bad_replies = [r['reply'] for r in fb_list if r['bad'] > r['good']][:5]")
w("            if not good_replies:")
w("                continue")
w("            current = get_learned_persona(self.data, gender)")
w("            good_str = chr(10).join(f'- {r}' for r in good_replies)")
w("            bad_str = (chr(10).join(f'- {r}' for r in bad_replies)) if bad_replies else ''")
w("            prompt = (")
w("                'You are improving a Discord chatbot personality.\\n\\n'")
w("                f'Current persona:\\n{current}\\n\\n'")
w("                f'Replies that got POSITIVE reactions (liked by users):\\n{good_str}\\n'")
w("                + (f'\\nReplies that got NEGATIVE reactions (disliked):\\n{bad_str}\\n' if bad_str else '')")
w("                + 'Rewrite the persona to be MORE like the positive examples and LESS like the negative ones. '")
w("                'Keep it under 4 sentences. Keep the unhinged/flirty/chaotic core. '")
w("                f'Gender context: {gender}. Return ONLY the new persona instruction text.'")
w("            )")
w("            new_persona = await _gemini(prompt, max_tokens=200)")
w("            if new_persona and len(new_persona) > 50:")
w("                self.data['learned_personas'][f'persona_{gender}'] = new_persona")
w("                self._log_action('auto_improve', 'global',")
w("                                 f'Persona evolved for gender={gender} ({len(good_replies)} good replies)')")
w("                logger.info(f'Auto-improved persona for gender={gender}')")
w("            await asyncio.sleep(5)")
w("        _save(self.data)")
w("")
w("    @self_improve_task.before_loop")
w("    async def before_self_improve(self):")
w("        await self.bot.wait_until_ready()")
w("        await asyncio.sleep(60)")
w("")
w("    @app_commands.command(name='ai-status', description='View AI Brain activity and auto-learn stats')")
w("    async def ai_status(self, interaction: discord.Interaction):")
w("        embed = discord.Embed(title='🧠 AI Brain Status', color=0x7c3aed if GEMINI_API_KEY else 0x6b7280)")
w("        embed.add_field(name='Gemini AI', value='✅ Active' if GEMINI_API_KEY else '❌ No API key', inline=True)")
w("        guild_id = str(interaction.guild.id)")
w("        embed.add_field(name='AI Moderation',")
w("                        value='✅ On' if guild_id in self._mod_enabled else '❌ Off', inline=True)")
w("        feedback = self.data.get('reply_feedback', {})")
w("        total_good = sum(r['good'] for g in feedback.values() for r in g)")
w("        total_bad = sum(r['bad'] for g in feedback.values() for r in g)")
w("        personas_improved = len(self.data.get('learned_personas', {}))")
w("        embed.add_field(")
w("            name='🧬 Auto-Learn Stats',")
w("            value=f'👍 Good reactions: **{total_good}**\\n👎 Bad reactions: **{total_bad}**\\nPersonas improved: **{personas_improved}/3**',")
w("            inline=False)")
w("        embed.add_field(")
w("            name='Capabilities',")
w("            value='• AI Moderation\\n• AI Welcome Messages\\n• Self-Improvement (every 6h)\\n• Auto-Learn from reactions\\n• Persona evolution',")
w("            inline=False)")
w("        guild_actions = [a for a in self.actions_log")
w("                         if a.get('guild') in (interaction.guild.name, 'global')][:6]")
w("        if guild_actions:")
w("            lines = []")
w("            for a in guild_actions:")
w("                ts = a['timestamp'][:16].replace('T', ' ')")
w("                lines.append(f'`{ts}` **{a[\"type\"]}**: {a[\"detail\"][:60]}')")
w("            embed.add_field(name='Recent AI Actions', value='\\n'.join(lines), inline=False)")
w("        else:")
w("            embed.add_field(name='Recent AI Actions', value='No actions yet.', inline=False)")
w("        embed.set_footer(text='Auto-improves every 6h based on reaction feedback')")
w("        await interaction.response.send_message(embed=embed, ephemeral=True)")
w("")
w("    @app_commands.command(name='ai-mod', description='Toggle AI auto-moderation for this server')")
w("    @app_commands.checks.has_permissions(manage_guild=True)")
w("    async def ai_mod_toggle(self, interaction: discord.Interaction):")
w("        guild_id = str(interaction.guild.id)")
w("        if guild_id in self._mod_enabled:")
w("            self._mod_enabled.discard(guild_id)")
w("            status, color = 'disabled', discord.Color.red()")
w("        else:")
w("            self._mod_enabled.add(guild_id)")
w("            status, color = 'enabled', discord.Color.green()")
w("        self._save_settings()")
w("        embed = discord.Embed(")
w("            title=f'🤖 AI Moderation {status}',")
w("            description=(")
w("                'AI will now detect and act on toxic messages.\\nActions: warn (6+), timeout (8+), delete (9+)'")
w("                if status == 'enabled' else 'AI moderation has been turned off.'")
w("            ),")
w("            color=color)")
w("        await interaction.response.send_message(embed=embed, ephemeral=True)")
w("")
w("    @app_commands.command(name='ai-welcome', description='Set AI-powered personalized welcome messages')")
w("    @app_commands.checks.has_permissions(manage_guild=True)")
w("    async def ai_welcome_setup(self, interaction: discord.Interaction, channel: discord.TextChannel):")
w("        if not GEMINI_API_KEY:")
w("            return await interaction.response.send_message('❌ GEMINI_API_KEY not set.', ephemeral=True)")
w("        guild_id = str(interaction.guild.id)")
w("        if 'settings' not in self.data:")
w("            self.data['settings'] = {}")
w("        settings = self.data['settings']")
w("        welcome_guilds = set(settings.get('ai_welcome_guilds', []))")
w("        welcome_guilds.add(guild_id)")
w("        settings['ai_welcome_guilds'] = list(welcome_guilds)")
w("        if 'ai_welcome_channels' not in settings:")
w("            settings['ai_welcome_channels'] = {}")
w("        settings['ai_welcome_channels'][guild_id] = str(channel.id)")
w("        _save(self.data)")
w("        await interaction.response.send_message(")
w("            f'✅ AI welcome enabled in {channel.mention}! Every new member gets a unique Gemini-generated welcome 🤖',")
w("            ephemeral=True)")
w("")
w("    @app_commands.command(name='ai-suggest', description='Ask AI for server improvement suggestions')")
w("    @app_commands.checks.has_permissions(manage_guild=True)")
w("    async def ai_suggest(self, interaction: discord.Interaction):")
w("        if not GEMINI_API_KEY:")
w("            return await interaction.response.send_message('❌ GEMINI_API_KEY not set.', ephemeral=True)")
w("        await interaction.response.defer(ephemeral=True)")
w("        guild = interaction.guild")
w("        stats = {}")
w("        if hasattr(self.bot, '_get_live_stats'):")
w("            stats = self.bot._get_live_stats(str(guild.id))")
w("        prompt = (")
w("            'You are an expert Discord community manager. Give 3 specific suggestions.\\n'")
w("            f'Server: {guild.name}\\nMembers: {guild.member_count}\\n'")
w("            f'Text channels: {len(guild.text_channels)}\\nRoles: {len(guild.roles)}\\n'")
w("            f'Messages today: {stats.get(\"messages\", 0)}\\nJoins today: {stats.get(\"joins\", 0)}\\n\\n'")
w("            'Give 3 numbered suggestions. Be specific and actionable. Each under 2 sentences.'")
w("        )")
w("        result = await _gemini(prompt, max_tokens=200)")
w("        if not result:")
w("            return await interaction.followup.send('❌ AI unavailable right now.', ephemeral=True)")
w("        embed = discord.Embed(title='🧠 AI Server Suggestions', description=result, color=0x7c3aed)")
w("        embed.set_footer(text='Powered by Gemini AI • Auto-improves every 6h')")
w("        await interaction.followup.send(embed=embed, ephemeral=True)")
w("")
w("")
w("async def setup(bot):")
w("    await bot.add_cog(AIBrain(bot))")

output = "\n".join(lines)
with open("cogs/ai_brain.py", "w", encoding="utf-8") as f:
    f.write(output)
print(f"Written {len(lines)} lines")
