[phases.setup]
nixPkgs = ["python311", "gcc", "ffmpeg", "libopus"]

[phases.install]
cmds = ["pip install -r requirements.txt", "pip install -U yt-dlp 'discord.py[voice]'"]

[start]
cmd = "python bot.py"
