services:
  - type: web
    name: WAN
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: CLAN_URL
        sync: false
      - key: ENABLE_DASHBOARD
        value: "true"
      - key: DASHBOARD_HOST
        value: "0.0.0.0"
      - key: DASHBOARD_SECRET_KEY
        sync: false
      - key: DASHBOARD_URL
        sync: false
